
services:
  postgres:
    image: postgres:latest
    container_name: atividade-api-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql