
services:
  postgres:
    image: postgres:latest
    container_name: atividade-api-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345678
      - DB_NAME=postgresdb
    depends_on:
      - postgres
